import {colors, fontFamily, scaleSize} from '../../../theme';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  blockDetail: {
    paddingTop: 24,
    paddingBottom: 12,
    borderTopColor: '#E6E6E6',
    borderTopWidth: 1,
  },
  blockDetailTitle: {
    ...fontFamily.fontWeight500,
    color: colors.primary,
    textTransform: 'uppercase',
    marginBottom: 20,
  },
  blockItemView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  blockItemName: {
    color: colors.primary,
    minWidth: 100,
    ...fontFamily.fontWeight500,
    fontSize: scaleSize(12),
  },
  blockItemValue: {
    color: colors.primary,
    ...fontFamily.fontWeight800,
    fontSize: scaleSize(14),
  },
  match: {
    fontSize: scaleSize(12),
    letterSpacing: 0.1,
    lineHeight: 20,
    color: colors.secondPrimary,
  },
  pointView: {
    width: 32,
    height: 32,
    backgroundColor: colors.secondPrimary,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  point: {
    color: 'white',
    fontSize: scaleSize(20),
    ...fontFamily.fontWeight900,
  },
  estimate: {
    color: 'black',
    fontSize: scaleSize(12),
    letterSpacing: 0.2,
    lineHeight: 18,
    textAlign: 'right',
    marginBottom: 18,
  },
  estimateValue: {
    color: 'black',
    fontSize: scaleSize(16),
    ...fontFamily.fontWeight800,
    lineHeight: 20,
  },
  name: {
    color: colors.secondPrimary,
    ...fontFamily.fontWeight800,
    marginBottom: 2,
  },
  company: {
    color: colors.textPrimary,
    fontSize: scaleSize(12),
    letterSpacing: 0.2,
    lineHeight: 16,
    marginBottom: 4,
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  specialized: {
    color: colors.primary,
    fontSize: scaleSize(12),
    letterSpacing: 0.1,
    lineHeight: 18,
    marginLeft: 10,
  },
  time: {
    color: colors.primary,
    fontSize: scaleSize(12),
    letterSpacing: 0.1,
    lineHeight: 18,
    marginLeft: 10,
    ...fontFamily.fontWeight800,
  },
  spaceBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  buttonBlock: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
    paddingHorizontal: 16,
  },
  block: {
    borderRadius: 16,
    paddingBottom: 16,
    width: '100%',
    overflow: 'hidden',
    marginRight: 16,
    flex: 1,
    backgroundColor: 'white',
  },
  suggestImage: {
    width: '100%',
    height: 200,
  },
  blockBody: {
    padding: 16,
    flex: 1,
  },
  suggestIconTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: 71,
    position: 'absolute',
    right: 16,
    top: 32,
    backgroundColor: colors.bgPrimary,
    height: 37,
    borderRadius: 8,
  },
  locationView: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    left: 16,
    bottom: 0,
    zIndex: 1,
    padding: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  locationName: {
    fontSize: scaleSize(14),
    ...fontFamily.fontWeight900,
    lineHeight: 18,
    color: 'white',
    marginLeft: 8,
  },
  titleModal: {
    fontSize: scaleSize(16),
    letterSpacing: 0.1,
    lineHeight: 20,
    color: colors.primary,
    marginBottom: 12,
    ...fontFamily.fontWeight800,
  },
  descriptionModal: {
    fontSize: scaleSize(14),
    letterSpacing: 0.1,
    lineHeight: 20,
    color: colors.primary,
    marginBottom: 8,
  },
});

export {styles};
